### ISSUE TITLE
[TASK] Development Environment Containerization Using Docker

### ISSUE THREAD

**Issue by CarlaShawi** [harismah/Dwella#10]
**Description:** Using Docker, we can establish a containerized development environment for our application and ensure it works consistently across different environments.

 - Developed docker files for server and client with necessary dependencies using the docker init command in the terminal 
 - Set up one docker-compose.yml to manage all services (frontend, backend, database)
 - In the root of the project, added a .env file which will include database credentials once set up
 
 PR to close this issue: #11

**Comment by harismah** [comment]
The Docker setup worked on my end for initializing the containerized development environment. Both the server and client containers are up and running smoothly using the docker-compose.yml file, and the necessary dependencies are in place. However, the database configuration will be handled in the following sprint, as discussed.

Since the setup is functioning as expected, I’m closing this issue. Everything looks good!
